# This file was generated by Nuitka

# Stubs included by default
import math

def solve(M2: typing.Any, d0_: typing.Any, Z0_: typing.Any, Zr_: typing.Any, wavelength: typing.Any, f: typing.Any) -> typing.Any:
    ...

__name__ = ...



# Modules used internally, to allow implicit dependencies to be seen:
import math